name: supabase_chat
description: "A simple chat application using Supabase written in Flutter."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^1.0.0
  timeago: ^3.1.0
  flutter_bloc: ^8.0.0
  cupertino_icons: ^1.0.8
  meta: ^1.15.0
  bloc: ^8.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
